packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@pixi/core": 6.5.10
  "@pixi/display": 6.5.10
  "@pixi/loaders": 6.5.10
  "@pixi/math": 6.5.10
  "@pixi/sprite": 6.5.10
  "@pixi/utils": 6.5.10

onlyBuiltDependencies:
  - esbuild
  - electron
  - msedge-tts
allowBuilds:
  9router: false
  esbuild: set this to true or false
  msedge-tts: set this to true or false
minimumReleaseAgeExclude:
  - electron@44.0.0
verifyDepsBeforeRun: false
