/**
 * Typed IPC channel names + payload shapes shared by main and preload.
 */
export const CHANNELS = {
  chatSend: "chat:send",
  chatToken: "chat:token",
  chatDone: "chat:done",
  chatError: "chat:error",
  chatThinking: "chat:thinking",
  chatAbort: "chat:abort",
  chatClear: "chat:clear",
  remember: "chat:remember",
  forget: "chat:forget",
  pointerShow: "pointer:show",
  pointerHide: "pointer:hide",
  gazeUpdate: "avatar:gaze",
  getStats: "chat:stats",
  chatResize: "chat:resize",
  openExternal: "shell:open-external",
  visionAsk: "vision:ask",
  setClickThrough: "overlay:set-clickthrough",
  ttsAudio: "tts:audio",
  chatProactive: "chat:proactive",
  avatarEmote: "avatar:emote",
  live2dSet: "avatar:live2d",
  live2dGet: "avatar:live2d-get",
  summonAt: "bar:summon-at",
  barDismissed: "bar:dismissed",
  barResize: "bar:resize",
  noteActivity: "activity:note",
  setupBegin: "setup:begin",
  setupBubble: "setup:bubble",
  setupMood: "setup:mood",
  setupStep: "setup:step",
  setupSubmit: "setup:submit",
  setupBack: "setup:back",
  setupDone: "setup:done",
  avatarReady: "avatar:ready",
  barReady: "bar:ready",
  setupActive: "setup:active",
  setupAudioEnd: "setup:audio-end",
} as const;

export type ChannelName = (typeof CHANNELS)[keyof typeof CHANNELS];
